### ISSUE TITLE
Fix moi ce github. On peut pas commit

### ISSUE THREAD

**Issue by ErdaBerda** [AurelienJt/Florimap#19]
je peux ni merge, ni commit. je sais pas ce que t'as encore fait mais si je peux pas travailler c'est pas ma faute. J'ai meme des erreurs de permission quand je fais une pull request

**Comment by ErdaBerda** [comment]
et comment on fait en sorte quon puisse merge mais que ca ferme pas la branche

**Comment by 0rangeFruit** [comment]
Ça tu fais merge et pas merge and close

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by AurelienJt** [comment]
Je n'ai pas changé de settings et Hendrick à réussi sans problème. C'est de ton coté que ca coince.

**Comment by ErdaBerda** [comment]
pourtant ca mamrchait absolument parfaitement avant que tu ne changes quoi que ce soit ehem.
enleve la verification de signature par contre, sinon je peux pas commit depuis vs code je dois me faire chier a aller sur github et a chaque CHAQUE CHAQUE fois commit depuis le site

**Comment by AurelienJt** [comment]
1: J'ai désactivé la vérification il y à bien des heures.

2: J'adorerai lever les restriciton, mais mon chois a été malheureusement confirmé par le comportement de certain.
