### ISSUE TITLE
Diviser le travail et faire des roles

### ISSUE THREAD

**Issue by ErdaBerda** [AurelienJt/Florimap#3]
pour éviter que yvain jacot font 90% et que nous on a rien a faire ensuite

**Comment by 0rangeFruit** [comment]
Je m'en occupe dès que g le temps donc peut être d'ici le prochain cours d'OC histoire d'avoir l'opinion de tout le monde si t ok avec ca

**Comment by 0rangeFruit** [comment]
Si ta des idées de rôles propose avec plaisir par contre

**Comment by ErdaBerda** [comment]
je pensais repartir le monde plutot, comme ca les gens qui codent moins ont aussi des choses a faire, ey jsp luiza meluzine peuvent s'amuser a convertir les plans en vecteur pour que nous on les implemente

**Comment by 0rangeFruit** [comment]
Je reformule : je m'occupe de répartir les tâches à tout le monde des que je peux, si tu as des idées de tâches donne les moi je les notes pour répartir

**Comment by OrnitOnGithub** [comment]
Why so serious?
![jonkle](https://github.com/user-attachments/assets/80d9c6c1-b487-473e-9244-528c6f18a31d)

**Comment by ErdaBerda** [comment]
## bro
# lis 
### en 
## entier 
#### ce 
## que 
### j'ai 
# ecrit 
-----
-----
-----
-----
-----
-----
-----
-----

**Comment by SchoolProject12345** [comment]
On pourrait juste assigner une personne par point de la TODO-list, et discuter lors du prochain cours au points qu'il faudrait peut-être rajouter.

**Comment by AurelienJt** [comment]
Prochain cours d'OC

**Comment by OrnitOnGithub** [comment]
No closing issues on my watch

**Comment by swisscookieman** [comment]
yes

**Comment by swisscookieman** [comment]
ice cream so good yes yes

**Comment by AurelienJt** [comment]
Please refer to https://github.com/AurelienJt/Florimap/discussions/6 for future task distribution.
This issue is now obsolete, I'll close it.

**Comment by OrnitOnGithub** [comment]
bitch
