### ISSUE TITLE
commit locked car un schizo a fait jspquoi avec branche main

### ISSUE THREAD

**Issue by ErdaBerda** [AurelienJt/Florimap#8]
c'est qui le schizo qui a fait je sais pas quelle fuckery avec la branche main, je peux pas commit je peux que creer une branche apart alors que j'ai juste update le todo.

**Comment by ErdaBerda** [comment]
Je vais pas faire une full branche apart pour faire 1 commit sur le todo

**Comment by OrnitOnGithub** [comment]
Ton répo local il était pas en retard de quelques commits par hasard? Si oui tu peux regler avec `git pull --rebase`

**Comment by OrnitOnGithub** [comment]
Ah bah j'ai testé et j'ai un permission denied (403)
```
remote: Permission to AurelienJt/Florimap.git denied to OrnitOnGithub.
fatal: unable to access 'https://github.com/AurelienJt/Florimap.git/': The requested URL returned error: 403
```
